# Generated by Django 3.1 on 2020-08-15 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
                ('friendly_name', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(max_length=254)),
                ('loc_address', models.CharField(blank=True, max_length=254, null=True)),
                ('loc_pc', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=254, null=True)),
                ('concert_name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
                ('concert_date', models.CharField(max_length=254)),
                ('concert_subtitle', models.CharField(blank=True, max_length=254, null=True)),
                ('concert_theme', models.CharField(blank=True, max_length=254, null=True)),
                ('concert_conductor', models.CharField(blank=True, max_length=254, null=True)),
                ('concert_soloist', models.CharField(blank=True, max_length=254, null=True)),
                ('concert_program', models.CharField(blank=True, max_length=254, null=True)),
                ('concert_time', models.TimeField(max_length=254)),
                ('concert_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('concert_image', models.ImageField(max_length=254, upload_to='')),
                ('edition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='concerts.edition')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='concerts.location')),
            ],
        ),
    ]
