# Generated by Django 3.1 on 2020-08-31 05:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(max_length=254)),
                ('loc_address', models.CharField(blank=True, max_length=254, null=True)),
                ('loc_pc', models.CharField(blank=True, max_length=8, null=True)),
                ('loc_place', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=254, null=True)),
                ('concert_name', models.CharField(default='name', max_length=254)),
                ('friendly_name', models.CharField(default='the full concert name', max_length=254)),
                ('concert_date', models.DateField(default=datetime.date.today, max_length=254)),
                ('concert_subtitle', models.CharField(blank=True, max_length=254, null=True)),
                ('concert_theme', models.CharField(blank=True, max_length=254, null=True)),
                ('concert_conductor', models.CharField(blank=True, max_length=254, null=True)),
                ('concert_soloist', models.CharField(blank=True, max_length=254, null=True)),
                ('concert_program', models.CharField(blank=True, max_length=254, null=True)),
                ('concert_description', models.TextField(blank=True, null=True)),
                ('concert_time', models.CharField(default='8 p.m.', max_length=254)),
                ('concert_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('concert_availability', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('concert_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('concert_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('edition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='concerts.edition')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='concerts.location')),
            ],
        ),
    ]
