# Generated by Django 3.1 on 2020-08-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0002_location_loc_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='concert_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
