# Generated by Django 3.1 on 2020-08-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0004_auto_20200815_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='concert_availability',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
    ]
