# Generated by Django 3.1 on 2020-08-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0005_auto_20200815_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='concert_date',
            field=models.DateField(blank=True, max_length=254, null=True),
        ),
    ]
