# Generated by Django 3.1 on 2020-08-29 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0006_auto_20200815_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='concert_date',
            field=models.DateField(default=datetime.date.today, max_length=254),
        ),
        migrations.AlterField(
            model_name='concert',
            name='concert_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='concert',
            name='concert_name',
            field=models.CharField(default='name', max_length=254),
        ),
        migrations.AlterField(
            model_name='concert',
            name='friendly_name',
            field=models.CharField(default='the full concert name', max_length=254),
        ),
    ]
