# Generated by Django 3.1 on 2020-08-29 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0007_auto_20200829_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='concert_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
