# Generated by Django 3.1 on 2020-08-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0010_auto_20200829_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='concert_time',
            field=models.CharField(default='8 p.m.', max_length=16),
        ),
        migrations.AlterField(
            model_name='edition',
            name='friendly_name',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='edition',
            name='name',
            field=models.CharField(max_length=16),
        ),
    ]
