# Generated by Django 3.1 on 2020-08-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0011_auto_20200829_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='edition',
            name='name',
            field=models.CharField(max_length=254),
        ),
    ]
