# Generated by Django 3.1 on 2020-08-30 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0013_auto_20200830_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='concert_date',
            field=models.DateField(default=datetime.date.today, max_length=254),
        ),
        migrations.AlterField(
            model_name='concert',
            name='concert_time',
            field=models.CharField(default='', max_length=16),
        ),
    ]
