# Generated by Django 3.1 on 2020-08-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0014_auto_20200830_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='concert_time',
            field=models.CharField(max_length=16),
        ),
    ]
