# Generated by Django 3.1 on 2020-08-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0016_auto_20200830_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='concert_time',
            field=models.CharField(default='8 p.m.', max_length=254),
        ),
    ]
