# Generated by Django 3.1 on 2020-08-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0017_auto_20200830_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='concert_date',
            field=models.DateField(default='', max_length=254),
        ),
    ]
