# Generated by Django 3.1 on 2020-08-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0019_auto_20200830_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='concert_date',
            field=models.CharField(default='16 October 2020', max_length=254),
        ),
    ]
